<h3 style="text-align: center;"><b>Установка</b></h3>

Подробную инструкцию по установке PyTorch вы можете найти на [официальном сайте PyTorch](https://pytorch.org/).

## Синтаксис Фреймворка

In [1]:
import torch

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.__version__

'1.14.0a0+410ce96'

Несколько фактов о PyTorch:
- динамический граф вычислений
- удобные модули `torch.nn` и `torchvision` для быстрого прототипирования нейронных сетей
- даже быстрее, чем TensorFlow на некоторых задачах
- позволяет легко использовать **GPU**

По своей сути PyTorch предоставляет две основные функции:

- n-мерный тензор, похожий на **numpy**, но может работать на графических процессорах
- Автоматическая дифференциация для построения и обучения нейронных сетей

Если бы PyTorch был формулой, она была бы такой:

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Давайте посмотрим, как мы можем использовать PyTorch для работы с векторами и тензорами.

Напомним, что **тензор** - это многомерный вектор, например :

`x = np.array ([1,2,3])` - вектор = тензор с 1 размерностью (точнее: `(3,)`)

`y = np.array ([[1, 2, 3], [4, 5, 6]])` - матрица = тензор с двумя измерениями (`(2, 3)` в данном случае)

`z = np.array ([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) `-" куб "(3, 3, 3) = тензор с тремя измерениями (` ( 3, 3, 3) `в этом случае)


Одним из реальных примеров трехмерного тензора является **изображение**, оно имеет 3 измерения: `высота`, `ширина` и `глубина канала` (глубина канала = 3 для цветных изображений, 1 для оттенков серого). Вы можете думать об этом как о параллелепипеде, состоящем из действительных чисел.


### Типы Тензоров

В PyTorch мы будем использовать `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) для всех вычислений.

Все типы:

In [3]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer
torch.IntTensor       # 32 бита, integer
torch.LongTensor      # 64 бита, integer

torch.CharTensor      # 8 бит, integer
torch.ByteTensor      # 8 бит, integer

torch.ByteTensor

Мы будем использовать только `torch.FloatTensor()` и `torch.IntTensor()`.

### Создание тензора

In [4]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [5]:
a.shape

torch.Size([2])

In [6]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
b.shape

torch.Size([2, 3])

In [8]:
x = torch.FloatTensor(2,3,4)

In [9]:
x

tensor([[[0.0000e+00, 0.0000e+00, 1.8788e+31, 1.7220e+22],
         [2.1715e-18, 1.3108e-08, 2.6407e-06, 1.3401e-08],
         [2.7329e-06, 1.3109e-08, 8.3388e-10, 2.1439e-07]],

        [[5.2942e-08, 4.2289e-05, 1.6985e-07, 2.1707e-18],
         [1.6678e+19, 7.0976e+22, 2.1715e-18, 4.2330e+21],
         [1.6534e+19, 1.1625e+27, 1.4580e-19, 7.1856e+22]]])

In [10]:
x = torch.FloatTensor(100)
x

tensor([ 4.5447e+30,  3.0750e+29,  1.9284e+31,  1.8891e+31,  8.3195e+35,
         2.1708e-18,  1.2059e+27,  3.0951e-18,  9.8686e+17,  1.7516e-43,
         5.6192e-43,  0.0000e+00,  2.2317e-11,  4.5600e-41,  2.2317e-11,
         4.5600e-41,  1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  4.9466e-43,  0.0000e+00,  1.8450e-34,
         0.0000e+00,  1.8470e-34,  0.0000e+00,  1.4013e-45,  0.0000e+00,
         6.6408e-35,  0.0000e+00,  1.8465e-34,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  2.6364e-37,  0.0000e+00,  2.0290e-35,  0.0000e+00,
        -2.2065e-14,  4.5597e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  9.8091e-45,
         0.0000e+00,  1.4013e-45,  0.0000e+00,  9.1

In [11]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Примечание:** если вы создаете `torch.Tensor` с помощью следующего конструктора, он будет заполнен мусором из "случайных номеров":

In [12]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[125117872,         0,     65793,  16843009],
         [        1,     65536,     65537,     65537]],

        [[        1,     65537,       257,         0],
         [        0,     65536,         0,         0]],

        [[    65537,  16843009,     65536,  16843009],
         [    65536,         1,       257,       257]]], dtype=torch.int32)

### Инициализации тензоров

In [13]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)

Инициализация случайного распределения

In [14]:
x = torch.randn((2,3))                # Normal(0, 1) с размером (2, 3)
x

tensor([[-1.1684, -2.6272,  0.3023],
        [ 0.2375, -0.1718,  0.2312]])

In [15]:
x.random_(0, 10)                      # Дискретное равномерное U[0, 10]
x.uniform_(0, 1)                      # Равномерное U[0, 1]
x.normal_(mean=0, std=1)              # Нормальное со средним 0 и дисперсией 1
x.bernoulli_(p=0.5)                   # Бернулли с параметром p

tensor([[0., 1., 1.],
        [0., 0., 0.]])

## Функции в Torch

У всех функций Numpy есть своя пара в Torch! Осталось теперь вспомнить numpy 🙂

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

### Изменение формы
`np.reshape()` == `torch.view()`:

In [16]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
b.view(3, 2).shape

torch.Size([3, 2])

In [18]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [19]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [20]:
b.view(2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Примечание:** `torch.view ()` создает новый тензор, но старый остается неизменным

### Изменение типа тензора

In [21]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [22]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [23]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [24]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [25]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

In [26]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [27]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [28]:
a[0, 0]

tensor(100.)

In [29]:
a[0:2, 1]

tensor([ 20., 163.])

### Арифметические операции

| операция | аналоги |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

#### Сложение

In [30]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [31]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [32]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [33]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [34]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

#### Вычитание

In [35]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [36]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [37]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [38]:
a.sub(b) # copy

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [39]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [40]:
a.sub_(b) # inplace

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [41]:
a

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

#### Умножение (поэлементное)

In [44]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

In [45]:
a * b

tensor([[ 5, 12],
        [21, 32]])

In [46]:
a.mul(b)

tensor([[ 5, 12],
        [21, 32]])

#### Деление (поэлементное):

In [47]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [48]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [49]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Примечание:** все эти операции создают новые тензоры, старые тензоры остаются неизменными.

In [50]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [51]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

### Операторы сравнения

In [52]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [53]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [54]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [55]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [56]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

### Использование индексации по логической маске

In [57]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [58]:
b[a == b]

tensor([100., 200., 300.])

### Поэлементное применение **универсальных функций**

Универсальная функция используется для описания функций, которые могут применяться поэлементно к тензорам и выполняют одну и ту же операцию на каждом элементе тензора.

In [59]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [60]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [61]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [62]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [63]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [67]:
a.log() # натуральный логарифм

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [68]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [69]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

### Агрегация и работа с осями
#### sum, mean, max, min:

In [70]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [71]:
a.shape

torch.Size([3, 3])

In [72]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [73]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [46]:
a.mean(dim=0)

tensor([ 37.,  74., 111.])

#### Применение функции вдоль оси

In [ ]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [ ]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [ ]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [ ]:
a.max()

tensor(300.)

In [ ]:
a.max(0)

torch.return_types.max(values=tensor([100., 200., 300.]), indices=tensor([2, 2, 2]))

**Примечание:** второй тензор, возвращаемый `.max()`, содержит индексы элементов max вдоль этой оси. Например. в этом случае `a.max ()` вернула `(100, 200, 300)`, которые являются минимальными элементами по оси 0 (вдоль столбцов), а их индексы по оси 0 равны `(2, 2, 2)`.


## Матричные операции

#### Транспонирование тензора

In [74]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [75]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

Это тоже не inplace-операция:

In [76]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

#### Скалярное произведение векторов

In [77]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [78]:
a.dot(b)

tensor(-141.)

In [79]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [80]:
a @ b

tensor(-141.)

In [81]:
type(a)

torch.Tensor

In [82]:
type(b)

torch.Tensor

In [83]:
type(a @ b)

torch.Tensor

#### Матричное произведение

In [84]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [85]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [86]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [87]:
a.matmul(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [88]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [89]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [90]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

Тензор `b` можно развернуть в одномерный массив с помощью функции `torch.view(-1)`, чтобы результат был вектором

In [91]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [92]:
b.view(-1)

tensor([ -1., -10., 100.])

In [93]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [94]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

## Конвертация
#### Конвертация из Numpy в Pytorch:

In [95]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.6529942 , 0.50777746, 0.6377586 ],
       [0.08120261, 0.55999048, 0.49047753],
       [0.60647774, 0.67777001, 0.9773639 ]])

In [96]:
b = torch.from_numpy(a)
b

tensor([[0.6530, 0.5078, 0.6378],
        [0.0812, 0.5600, 0.4905],
        [0.6065, 0.6778, 0.9774]], dtype=torch.float64)

**Внимание!** `a` и `b` хранятся в одной и той же ячейке данных. Если именить один тензор, то изменится и другой.

In [97]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [98]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Конвертация из Torch в Numpy

In [99]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[1.8617e-34, 0.0000e+00, 2.6452e-37, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 1.1351e-43, 0.0000e+00],
         [1.8558e-34, 0.0000e+00, 2.2316e-11, 4.5600e-41],
         [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]]])

In [100]:
type(a)

torch.Tensor

In [101]:
x = a.numpy()
x

array([[[1.8616892e-34, 0.0000000e+00, 2.6452461e-37, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 1.4012985e-45, 0.0000000e+00]],

       [[0.0000000e+00, 0.0000000e+00, 1.1350518e-43, 0.0000000e+00],
        [1.8557786e-34, 0.0000000e+00, 2.2316426e-11, 4.5599653e-41],
        [1.4012985e-45, 0.0000000e+00, 1.4012985e-45, 0.0000000e+00]]],
      dtype=float32)

In [102]:
x.shape

(2, 3, 4)

In [103]:
type(x)

numpy.ndarray

In [104]:
x -= x

In [105]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## <h1 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

CUDA --- это программно-аппаратная архитектура параллельных вычислений, которая позволяет существенно увеличить вычислительную производительность благодаря использованию графических процессоров фирмы Nvidia. Для нас CUDA --- это драйвер, который позволяет нам проводить вычисления на GPU.

[CUDA documentation](https://docs.nvidia.com/cuda/)

Для вычислений на Pytorch мы можем использовать как CPU (Central Processing Unit), так и GPU (Graphical Processing Unit). Между ними можно легко переключаться, и это очень важно!

In [130]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.2865, 0.1246, 0.1817,  ..., 0.2746, 0.2980, 0.4204],
        [0.6218, 0.2908, 0.2601,  ..., 0.3198, 0.0231, 0.0312],
        [0.7858, 0.9737, 0.3149,  ..., 0.5433, 0.8013, 0.3028],
        ...,
        [0.8839, 0.0853, 0.6754,  ..., 0.1506, 0.9244, 0.0803],
        [0.6538, 0.3602, 0.4594,  ..., 0.5801, 0.3725, 0.6669],
        [0.9593, 0.3496, 0.5332,  ..., 0.3113, 0.9677, 0.7203]])

In [131]:
x.is_cuda

False

#### Кладём тензор на GPU

In [132]:
!nvidia-smi

Fri Feb  9 15:36:22 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:1A:00.0 Off |                    0 |
| N/A   49C    P0    28W /  70W |    579MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:1B:00.0 Off |                    0 |
| N/A   

In [133]:
x = x.cuda()

In [134]:
!nvidia-smi

Fri Feb  9 15:36:26 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:1A:00.0 Off |                    0 |
| N/A   49C    P0    28W /  70W |    619MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:1B:00.0 Off |                    0 |
| N/A   

In [135]:
x

tensor([[0.2865, 0.1246, 0.1817,  ..., 0.2746, 0.2980, 0.4204],
        [0.6218, 0.2908, 0.2601,  ..., 0.3198, 0.0231, 0.0312],
        [0.7858, 0.9737, 0.3149,  ..., 0.5433, 0.8013, 0.3028],
        ...,
        [0.8839, 0.0853, 0.6754,  ..., 0.1506, 0.9244, 0.0803],
        [0.6538, 0.3602, 0.4594,  ..., 0.5801, 0.3725, 0.6669],
        [0.9593, 0.3496, 0.5332,  ..., 0.3113, 0.9677, 0.7203]],
       device='cuda:0')

In [136]:
x = x.cpu().detach()
del x
torch.cuda.empty_cache()
!nvidia-smi

Fri Feb  9 15:36:30 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:1A:00.0 Off |                    0 |
| N/A   49C    P0    28W /  70W |    619MiB / 15109MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:1B:00.0 Off |                    0 |
| N/A   

In [113]:
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")

x = x.to(device)
x

tensor([[0.0677, 0.2616, 0.0333,  ..., 0.7720, 0.3502, 0.0513],
        [0.9806, 0.4155, 0.4296,  ..., 0.4077, 0.8897, 0.8949],
        [0.9110, 0.5538, 0.5530,  ..., 0.3764, 0.5964, 0.5805],
        ...,
        [0.6196, 0.5529, 0.6042,  ..., 0.0613, 0.6647, 0.0159],
        [0.5222, 0.8412, 0.4637,  ..., 0.7849, 0.9551, 0.8379],
        [0.0075, 0.4646, 0.9329,  ..., 0.5991, 0.9607, 0.8722]],
       device='cuda:0')

Умножим два тензора в GPU и вернём результат обратно на CPU:

In [114]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [115]:
c

tensor([[0.1609, 0.2306, 0.0032,  ..., 0.4591, 0.1394, 0.5672],
        [0.6999, 0.1064, 0.6273,  ..., 0.0261, 0.0548, 0.0836],
        [0.3557, 0.0153, 0.1673,  ..., 0.0088, 0.3282, 0.3525],
        ...,
        [0.0383, 0.1347, 0.1580,  ..., 0.0305, 0.6656, 0.3184],
        [0.1211, 0.1444, 0.4060,  ..., 0.3453, 0.0120, 0.5279],
        [0.0611, 0.4763, 0.4933,  ..., 0.0018, 0.0873, 0.6774]])

In [116]:
a

tensor([[0.8542, 0.8903, 0.9784,  ..., 0.5470, 0.1793, 0.9003],
        [0.8757, 0.5662, 0.9825,  ..., 0.2071, 0.1193, 0.7909],
        [0.4161, 0.1702, 0.5115,  ..., 0.0205, 0.3445, 0.8182],
        ...,
        [0.1940, 0.4188, 0.8242,  ..., 0.0515, 0.8341, 0.4170],
        [0.3411, 0.3192, 0.5302,  ..., 0.5619, 0.0703, 0.7270],
        [0.0758, 0.5901, 0.8698,  ..., 0.9635, 0.4473, 0.6977]])

Тензоры из разных областей памяти не совместимы:

In [117]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [118]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

## Дополнительные материалы

*1). Official PyTorch tutorials: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*2). arXiv article about the deep learning frameworks comparison: https://arxiv.org/pdf/1511.06435.pdf*

*3). Useful repo with different tutorials: https://github.com/yunjey/pytorch-tutorial*

*4). Facebook AI Research (main contributor of PyTorch) website: https://facebook.ai/developers/tools*