<h1 style="text-align: center;"><b>Практика 1</b></h1>

<h2 style="text-align: center;"><b>Библиотека NumPy</b></h1>

In [1]:
%%time
arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

CPU times: user 1.63 s, sys: 229 ms, total: 1.86 s
Wall time: 1.87 s


**Что будет, если переписать этот код на NumPy**

In [2]:
import numpy as np

In [7]:
%%time

n = 10**7
arr = np.arange(n) * 5

CPU times: user 12.9 ms, sys: 19.9 ms, total: 32.8 ms
Wall time: 33.9 ms


# Библиотека Numpy.
- **``Numpy`` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.**


- **Пакет ``Numpy`` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В ``Numpy`` реализовано много операций над массивами в целом.**

In [ ]:
# !conda install numpy
# !pip3 install numpy

In [1]:
import numpy as np

## 1. Одномерные массивы

In [2]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), type(a))

<class 'numpy.ndarray'> <class 'list'>


**Например узнаем размер массива.**

In [3]:
arr = np.array([5, 6, 2, 1, 10], dtype='int32')

In [4]:
arr.shape

(5,)

## 2. Двумерные массивы

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]], float)

In [6]:
arr.shape

(2, 3)

**Если вы не знаете нужной функции, но понимаете, чего хотите, тогда можно воспользоваться поиском в документации.**

In [7]:
np.lookfor('mean value of array')

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.isrealobj
    Return True if x is a not complex type or an array of complex numbers.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Retur

***Далее можно почитать документацию про контретную функцию.***

In [8]:
?np.ma.mean

Signature:       np.ma.mean(a, *args, **params)
Type:            _frommethod
String form:     <numpy.ma.core._frommethod object at 0x7f6cce172880>
File:            /usr/local/lib/python3.8/dist-packages/numpy/ma/core.py
Docstring:      
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average : Weighted average.

Examples
--------
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
Class docstring:
Define functions from existing MaskedArray methods.

Parameters
----------
methodname : str
    Name of the method to transform.


In [9]:
np.con*?

np.concatenate
np.conftest
np.conj
np.conjugate
np.convolve

**Посмотрим на количественные характеристики ``ndarray``.**

In [10]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]],
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [11]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.",
      "\nshape first matrix:", arr[0].shape, "-- количество элементов первой матрицы")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
shape: (2, 3, 4) -- количество элементов по каждой оси. 
shape first matrix: (3, 4) -- количество элементов первой матрицы


**Индексы.**

In [12]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

(1, 2)

**Последний элемент.**

In [13]:
a[-1]

4

**Можем изменять объекты массива.**

In [14]:
a[2] = -1
a

array([ 1,  2, -1,  4])

**``ndarray`` можно использовать в циклах. Но при этом теряется главное преимущество `Numpy` -- быстродействие. Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.**

In [15]:
for i in a:
    print(i)

1
2
-1
4


**Задача 1:** Создать numpy-массив, состоящий из первых четырех простых чисел, выведите его тип и размер в байтах:

In [16]:
# решение

arr = np.array([2, 3, 5, 7], dtype=np.float32)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes) # 32 bit = 32 / 8 = 4 bytes, 4 elements * 4 bytes = 16 bytes

[2. 3. 5. 7.]
float32
<class 'numpy.ndarray'>
(4,)
16


## Создание массивов.

In [17]:
a = np.zeros(7, dtype=np.int16) # массив из нулей
b = np.ones(7, dtype=np.float64) # массив из единиц
print(a)
print(b)

[0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1.]


**Часто нужно создать нулевой массив такой же как другой.**

In [18]:
c = np.zeros(7, dtype=np.float64)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [19]:
c = np.zeros_like(b, dtype=np.int64)
c

array([0, 0, 0, 0, 0, 0, 0])

**Функция `np.arange` подобна `range`. Аргументы могут быть с плавающей точкой.**

In [20]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 0.2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5.   5.2  5.4  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6
  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4
 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2
 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8 15.  15.2 15.4 15.6 15.8 16.
 16.2 16.4 16.6 16.8 17.  17.2 17.4 17.6 17.8 18.  18.2 18.4 18.6 18.8
 19.  19.2 19.4 19.6 19.8 20.  20.2 20.4 20.6 20.8]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


**Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент -- число точек.**

In [22]:
a = np.linspace(1, 15, 20)
b = np.linspace(5, 12, 10)
print(a)
print(b)

[ 1.          1.73684211  2.47368421  3.21052632  3.94736842  4.68421053
  5.42105263  6.15789474  6.89473684  7.63157895  8.36842105  9.10526316
  9.84210526 10.57894737 11.31578947 12.05263158 12.78947368 13.52631579
 14.26315789 15.        ]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


**Задача 2:** создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности -- 12. Чему равен шаг?

In [23]:
# решение

a = np.linspace(10, 32, 12)
print(a)
print(a[1] - a[0])



[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


**Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$.**

In [24]:
b = np.logspace(0, 3, 12)
print(b)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


# 2. Операции над одномерными массивами.

**Все арифметические операции производятся поэлементно.**

In [25]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a)
print(b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]


In [26]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


**Один из операндов может быть скаляром, а не массивом.**

In [28]:
print(5*a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [29]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


**Если типы элементов разные, то идет преобразование к большему.**

In [30]:
print(type(a[0]))
b = a + np.arange(11, dtype='int16')
print(type(b[0]))

<class 'numpy.float64'>
<class 'numpy.float64'>


**При делении ``ndarray`` на нули, исключения не бросается.**

In [32]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))

[  0.  nan  inf -inf]


/tmp/ipykernel_365/3088186758.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))
/tmp/ipykernel_365/3088186758.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))


**Могут понадобится константы.**

In [34]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


In [35]:
print(b)
print(b.cumsum())

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43.]
[  3.  10.  21.  36.  55.  78. 105. 136. 171. 210. 253.]


**Посмотрим на сортировку numpy-массивов.**

In [36]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [37]:
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 18]
[ 1  5  6 10 -2  0 18]


**Функции ``append`` ``delete`` ``insert``.**

In [38]:
print(np.delete(a, [2, 4, 1]))
print(a)

[ 1 10  0 18]
[ 1  5  6 10 -2  0 18]


In [39]:
np.insert(a, 2, [-1, -1])

array([ 1,  5, -1, -1,  6, 10, -2,  0, 18])

In [40]:
np.append(a, [2.2, 2.1])

array([ 1. ,  5. ,  6. , 10. , -2. ,  0. , 18. ,  2.2,  2.1])

## Индексирование массивов и срезы

**Массив в обратном порядке.**

In [41]:
a[::-1]

array([18,  0, -2, 10,  6,  5,  1])

**Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.**

In [42]:
print(a)

[ 1  5  6 10 -2  0 18]


In [43]:
a[2:5]

array([ 6, 10, -2])

In [44]:
b = a[0:6] # копия не создается
b[1] = -1000
print(a)

[    1 -1000     6    10    -2     0    18]


**Диапозоны с шагами.**

In [45]:
b = a[0:4:2]
print(b)

# подмассиву можно присваивать скаляр
a[1:6:3] = 0
print(a)

[1 6]
[ 1  0  6 10  0  0 18]


**Чтобы скопировать и данные массива, нужно использовать метод ``copy``.**

In [46]:
b = a.copy()
b[2] = -4
print(b)
print(a)

[ 1  0 -4 10  0  0 18]
[ 1  0  6 10  0  0 18]


In [47]:
print(a[[5,3,1]]) # массив индексов

[ 0 10  0]


# 3. Обращение в двумерных массивах

In [48]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [49]:
a.ndim, a.shape, len(a), a.size

(2, (2, 2), 2, 4)

**Обращение по индексу.**

In [50]:
a[1][1], a[1,1]

(4, 4)

**Атрибуту ``shape`` можно присвоить новое значение -- кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.**

In [51]:
b = np.arange(0, 20)
b.shape = (2, 10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [52]:
print(b.ravel()) # стягивание в одномерный массив

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
a = np.ones((3, 3)) # подать tuple
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
b = np.zeros((3, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
d = np.diag([1, 2, 3, 'a'])
print(d)

[['1' '' '' '']
 ['' '2' '' '']
 ['' '' '3' '']
 ['' '' '' 'a']]


**Умножение матриц.**

In [57]:
a = 5 * np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [59]:
print(a * b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b))

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


**Маски.**

In [60]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


**След (trace) - сумма диагональных элементов.**

In [ ]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


# 4. Тензоры (многомерные массивы)

Тензор - структура данных, используемая в вычислительных фреймворках и библиотеках для работы с многомерными массивами. Обобщают концепцию скаляров, векторов и матриц на более высокие размерности.

Отличие тензоров NumPy от тензоров PyTorch: не переносятся на GPU и не поддерживают автоматического дифференциирования.

In [61]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [62]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

**Посмотрим на суммы по разным осям.**

In [63]:
print(0+8+16+24+32+40+48+56) # axis = 0
print(0+4, 1+5, 2+6, 3+7) # axis = 1
print(0+1+2+3) # axis = 3

224
4 6 8 10
6


In [64]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

print(np.sum(X, axis=(1, 2)))

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


# 5. Линейная алгебра

In [65]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


**Определитель.**

In [66]:
np.linalg.det(a)

4.0

**Транспонирование.**

In [67]:
a.T

array([[2, 2],
       [1, 3]])

**Нахождений обратной матрицы.**

In [68]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [69]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


**Дерерминант = 0 -> сообщение об ошибке**

In [70]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


In [71]:
np.linalg.inv(c)

LinAlgError: Singular matrix

**Решение матричных уравнений.**
$$
\begin{pmatrix}
2 & 3 \\
4 & 1
\end{pmatrix}
X =
\begin{pmatrix}
5 & 7 \\
8 & 2
\end{pmatrix}
$$

In [72]:
import numpy as np

A = np.array([[2, 3], [4, 1]])
B = np.array([[5, 7], [8, 2]])

X = np.linalg.solve(A, B)

print(X)

[[ 1.9 -0.1]
 [ 0.4  2.4]]


In [73]:
X = np.linalg.inv(A).dot(B)
print(X)

[[ 1.9 -0.1]
 [ 0.4  2.4]]


## 6. Распределения

In [74]:
# Генерация выборки из нормального распределения с параметрами среднего (mean) и стандартного отклонения (std)
mean = 2
std = 4
normal_distribution = np.random.normal(mean, std, size=1000)
standard_normal_distribution = np.random.randn(1, 1000)

In [75]:
# Генерация выборки из равномерного распределения на отрезке [low, high)
low = 0
high = 10
uniform_distribution = np.random.uniform(low, high, size=1000)

In [76]:
# Генерация выборки из экспоненциального распределения с параметром lambda
# lambda - среднее число событий, происходящих за единицу времени
lambda_param = 0.5
exponential_distribution = np.random.exponential(lambda_param, size=1000)

In [77]:
# Генерация выборки из биномиального распределения с параметрами n (число испытаний) и p (вероятность успеха)
n = 10
p = 0.5
binomial_distribution = np.random.binomial(n, p, size=1000)

In [78]:
# Генерация выборки из геометрического распределения с параметром p (вероятность успеха)
p = 0.3
geometric_distribution = np.random.geometric(p, size=1000)

# Полезные ссылки

In [43]:
np.random.seed(1)

a = np.random.rand(3,3)
b = a.max(1)

In [44]:
b.shape

(3,)

In [47]:
import numpy as np

np.random.seed(1)

x = np.random.randn(1,10)
b = mean = 0
std = 1
normal_distribution = np.random.normal(0, 1, size=10)

In [48]:
x

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
        -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038]])

In [49]:
normal_distribution

array([ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521])

[Введение в Анализ Данных](https://mipt-stats.gitlab.io/jekyll/update/2020/02/01/ad.html)

[GitHub NumPy](https://github.com/numpy/numpy)

[Документация по NumPy](https://numpy.org/doc/stable/)

[mlcource.ai](https://mlcourse.ai)