In [2]:
import numpy as np

1. Создать вектор (одномерный массив) размера 10, заполненный нулями

In [5]:
t = np.zeros(10)
print(t,t.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)


2. Создать вектор размера 10, заполненный двойками

In [6]:
t = np.ones(10)*2
print(t,t.shape)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.] (10,)


3. Создать вектор со значениями от 5 до 100

In [7]:
t = np.arange(5,101)
print(t)

[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100]


4. Создать вектор со значениями от 5 до 100, возвести в квадрат все элементы и посчитать сумму

In [8]:
t = (np.arange(5,101)**2).sum()
print(t)

338320


5. Развернуть вектор

In [14]:
t = np.arange(10)
t_flip = t[::-1]
t_flip_1 = np.flip(t)
print(t_flip,t_flip_1)

[9 8 7 6 5 4 3 2 1 0] [9 8 7 6 5 4 3 2 1 0]


6. Создать матрицу 4x3 со значениями от 0 до 11 и развенуть по нулевой размерности

In [21]:
t = np.arange(12)
T = t.reshape(4,3)
print(T)
T_flip = T[::-1,:] # T_flip = np.flipud(T)
print(T_flip)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]


7. Создать матрицу 4х3 случайных чисел из нормального распределения. Найти индекты элементов, которые больше нуля

In [27]:
t = np.random.randn(4,3)
idx = t>0
true_indices = [(i, j) for i, row in enumerate(idx) for j, value in enumerate(row) if value]

print(true_indices)
print(idx)

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (3, 0), (3, 1)]
[[ True  True False]
 [ True  True False]
 [ True False False]
 [ True  True False]]


8. Создать матрицу 4х3 случайных чисел из нормального распределения. Сделать нормировку элеметнов (каждая колонка матрицы - это характеристика)
$$ \frac{x-min(x)}{max(x) - min(x)} $$

In [34]:
t = np.random.randn(4,3)
t_norm = (t - t.min(0))/(t.max(0)-t.min(0))
t_norm

array([[1.        , 1.        , 0.1369147 ],
       [0.        , 0.31901445, 0.44640012],
       [0.91199365, 0.        , 1.        ],
       [0.79831449, 0.52973322, 0.        ]])

9. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [37]:
t = np.zeros((8,8), dtype=int)
t[1::2,::2] = 1
t[::2,1::2] = 1
print(t)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


10. Сделать сортировку вектора

In [43]:
t = np.random.randn(10)
print(np.sort(t))

[-2.25236874 -1.33263018 -0.87300058 -0.79386298 -0.257896    0.04802981
  0.09120194  0.35093335  1.41911862  1.47556765]


11. Заменить максимальный элемент на минимальный

In [45]:
t = np.random.randn(6)
print(t)
t[t == t.max()] = t.min()
print(t)

[ 0.12585409 -0.05334682 -0.47013808  0.76473484  0.58528855 -0.07385427]
[ 0.12585409 -0.05334682 -0.47013808 -0.47013808  0.58528855 -0.07385427]


12. Дан массив точек 10х2. Найти все попарные расстояния между точками

In [55]:
t = np.random.randn(10,2)
t_unsq =  np.expand_dims(t, axis=1) # t[:,np.newaxis, :] 
dist = np.sqrt((t_unsq - t)**2)
dist[:,:,0]

array([[0.        , 0.37267858, 1.88559622, 0.73161241, 1.28738222,
        1.11669211, 0.08054023, 1.62872304, 1.27014416, 1.52992167],
       [0.37267858, 0.        , 1.51291764, 0.35893383, 0.91470364,
        0.74401353, 0.29213835, 1.25604446, 0.89746558, 1.90260025],
       [1.88559622, 1.51291764, 0.        , 1.15398381, 0.598214  ,
        0.76890411, 1.80505598, 0.25687318, 0.61545206, 3.41551788],
       [0.73161241, 0.35893383, 1.15398381, 0.        , 0.55576981,
        0.3850797 , 0.65107218, 0.89711063, 0.53853175, 2.26153408],
       [1.28738222, 0.91470364, 0.598214  , 0.55576981, 0.        ,
        0.17069011, 1.20684199, 0.34134082, 0.01723806, 2.81730389],
       [1.11669211, 0.74401353, 0.76890411, 0.3850797 , 0.17069011,
        0.        , 1.03615187, 0.51203093, 0.15345205, 2.64661377],
       [0.08054023, 0.29213835, 1.80505598, 0.65107218, 1.20684199,
        1.03615187, 0.        , 1.54818281, 1.18960393, 1.6104619 ],
       [1.62872304, 1.25604446, 0.2568731

13. Найти норму Фробениуса матрицы 4х4
$$ norma = trace(A^T A) $$

In [61]:
A = np.random.randn(5,5)
norma = (np.diag(A.T@A)).sum()
print(norma)

18.281024593377566


14. Объединить два массива размером 3х3 по 3-й оси

In [67]:
t1,t2 = np.random.rand(3,3),np.random.rand(3,3)

z = np.stack([t1,t2],axis=2)
z.shape

(3, 3, 2)